

model:
  name: "roberta-base"

task:
  path: None
  dataset_name: "squad"
  task_name: "plain_text"

results:
  output_path: "squad"

train:
  epochs: 2
  batch: None
  samples: 500

run:
  seeds: 2